server:
  port: 80

spring:
  datasource:                                           # Data source configuration
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    password: imooc